
let stocks=[]; const fmtUSD=n=>n==null?'—':n.toLocaleString(undefined,{style:'currency',currency:'USD'}); const fmtPct=n=>n==null?'—':`${Number(n).toFixed(2)}%`;
async function load(){stocks=await fetch('data/stocks.json').then(r=>r.json()); setupFilters(); render(); calcIncome();}
function setupFilters(){const sectors=[...new Set(stocks.map(s=>s.sector).filter(Boolean))].sort(); const sel=document.getElementById('sector'); sectors.forEach(s=>sel.insertAdjacentHTML('beforeend',`<option>${s}</option>`)); ['search','sector','signal'].forEach(id=>document.getElementById(id).addEventListener('input',render));}
function signalClass(s){s=(s||'WATCH').toUpperCase(); if(s.includes('BUY'))return'buy'; if(s.includes('AVOID')||s.includes('NO'))return'avoid'; return'watch'}
function filtered(){const q=document.getElementById('search').value.toLowerCase(),sec=document.getElementById('sector').value,sig=document.getElementById('signal').value; return stocks.filter(s=>(!q||s.ticker.toLowerCase().includes(q)||s.name.toLowerCase().includes(q))&&(!sec||s.sector===sec)&&(!sig||(s.signal||'').toUpperCase().includes(sig)));}
function render(){const data=filtered().sort((a,b)=>(b.trqxScore||0)-(a.trqxScore||0)); document.getElementById('rows').innerHTML=data.map(s=>`<tr><td><b>${s.ticker}</b><div class="small">${s.exchange}</div></td><td>${s.name}</td><td>${s.sector}</td><td>${fmtUSD(s.price)}</td><td>${fmtUSD(s.low52)}</td><td>${fmtUSD(s.high52)}</td><td>${fmtPct(s.from52LowPct)}</td><td>${fmtPct(s.below52HighPct)}</td><td><span class="pill ${signalClass(s.signal)}">${s.signal||'WATCH'}</span></td><td class="score">${s.trqxScore}</td></tr>`).join(''); document.getElementById('kpiStocks').textContent=stocks.length; document.getElementById('kpiBuys').textContent=stocks.filter(s=>(s.signal||'').toUpperCase().includes('BUY')).length; document.getElementById('kpiScore').textContent=Math.round(stocks.reduce((a,b)=>a+(b.trqxScore||0),0)/stocks.length); document.getElementById('kpiCost').textContent=fmtUSD(stocks.reduce((a,b)=>a+(b.cost100||0),0)); const top=stocks.slice().sort((a,b)=>(b.trqxScore||0)-(a.trqxScore||0)).slice(0,10); document.getElementById('topList').innerHTML=top.map(s=>`<div><b>${s.ticker}</b> <span class="small">${s.name}</span><div class="bar"><span style="width:${s.trqxScore}%"></span></div></div>`).join('');}
function calcIncome(){const p=+document.getElementById('portfolio').value||0,y=(+document.getElementById('yield').value||0)/100; document.getElementById('annualIncome').textContent=fmtUSD(p*y); document.getElementById('monthlyIncome').textContent=fmtUSD(p*y/12);}
async function refreshQuotes(){try{const symbols=stocks.map(s=>s.ticker).join(','); const res=await fetch(`/api/quotes?symbols=${encodeURIComponent(symbols)}`); if(!res.ok) throw new Error('API not configured'); const quotes=await res.json(); const map=Object.fromEntries(quotes.map(q=>[q.symbol,q])); stocks=stocks.map(s=>{const q=map[s.ticker]; if(!q)return s; const price=q.price||s.price; return {...s,price,previousClose:q.previousClose||s.previousClose,from52LowPct:s.low52?((price-s.low52)/s.low52*100):s.from52LowPct,below52HighPct:s.high52?((s.high52-price)/s.high52*100):s.below52HighPct};}); render();}catch(e){alert('Live API is not connected yet. Deploy to Vercel and add FMP_API_KEY, or wire this to your preferred market-data API.');}}
load();
